### ISSUE TITLE
{playlists} returns just one playlist

### ISSUE THREAD

**Issue by LordHelmchen666** [Moonbase59/azuracast_xmltv#3]
In "gap_filler":
 - {playlists}* -- comma-separated list of playlist names that make up the general rotation

{playlists} returns just one playlist. "Rock und Deutsch-Rock" which is the default one. Should it not return all (public) playlists?

**Comment by Moonbase59** [comment]
No really. It’s supposed to return the playlists that actually "feed" the gaps in between scheduled blocks, i.e. those that make up the general rotation. To show up in `{playlists}`, these must

- be enabled
- be of type "default"
- not be on a schedule

I have, for example, these playlists that make up the general rotation:

- `Classic Rock` (weight 3),
- `Folk Rock` (weight 1), and
- `Hard Rock` (weight 3).

My `{playlists}` returns `Classic Rock, Folk Rock & Hard Rock`.

Wouldn’t make sense to show _all_ my 63 playlists to a listener, would it?

Hope this clarifies the ide a little.

**Comment by LordHelmchen666** [comment]
That makes sense. So this should be left as it is.

**Comment by Moonbase59** [comment]
That’s what I hoped for… ;-) Let’s close this one.
